repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# -   repo: https://github.com/psf/black
#     rev: 21.12b0
#     hooks:
#     -   id: black
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.33.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
    # -   id: commitizen-branch
    #     stages: [push]
-   repo: local
    hooks:
    -   id: export-poetry
        name: Export requirements.txt
        language: system
        entry: bash -c  "poetry export -f requirements.txt -o requirements.txt"
    -   id: export-poetry-dev
        name: Export dev dependencies
        language: system
        entry: bash -c  "poetry export -f requirements.txt -o requirements-dev.txt  --with=dev"
    -   id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^(src/|tests/)
    # -   id: poetry-export # generate a requirements.txt file from the pyproject.toml
        # args: ["-f", "requirements.txt", "-o", "requirements.txt"]
