repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# -   repo: https://github.com/psf/black
#     rev: 21.12b0
#     hooks:
#     -   id: black
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages: [push]
-   repo: local
    hooks:
    -   id: run-poetry
        name: run-poetry
        language: system
        entry: bash -c  "poetry export -f requirements.txt -o requirements.txt"
    -   id: black
        name: black
        language: system
        entry: bash -c  "black --include *.py"
    # -   id: poetry-export # generate a requirements.txt file from the pyproject.toml
        # args: ["-f", "requirements.txt", "-o", "requirements.txt"]
